/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package EmailSender;

import cli.Console;
import commands.CommandFactory;
import commands.CommandInvoker;
import commands.ICommand;

import java.util.ArrayList;

public class App {
    public static void main(String[] args) {
        Console console = new Console();
        ArrayList<ICommand> appCommands = CommandFactory.createTestAppCommendList(console);
        CommandInvoker invoker = new CommandInvoker(appCommands, console, "Evaluation task:   Galal Ahmed {galal.omar.ahmed@gmail.com}");
        invoker.run();
    }
}
